name: Pull Request Labeler

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  labeler:
    runs-on: ubuntu-latest
    name: Pull request labeler
    steps:
      - uses: actions/checkout@v2
        name: Checkout branch
      - uses: IvanFon/super-labeler-action@master
        name: Label pull request
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
          config: '.github/workflows/pr-labeler-config.json'